# Tomcat
server:
    tomcat:
        uri-encoding: UTF-8
        max-threads: 1000
        min-spare-threads: 30
    port: 8080
    connection-timeout: 5000ms
spring:
    # 环境 dev|test|prod
    profiles:
        active: dev
    http:
        multipart:
            enabled: true
            max-file-size: 100MB
            max-request-size: 100MB

    thymeleaf:
      suffix: .thtml
      cache: false
    freemarker:
          suffix: .html
          request-context-attribute: request
# 集群配置
    redis:
        #clusterNodes: 39.107.227.83:7001,39.107.227.83:7002,39.106.54.47:7003,39.106.54.47:7004,39.107.107.107:7005,39.107.107.107:7006
        cluster:
            nodes:
                - 192.168.254.204:7001
                - 192.168.254.204:7002
                - 192.168.254.205:7003
                - 192.168.254.205:7004
                - 192.168.254.206:7005
                - 192.168.254.206:7006
        expireSeconds: 60
        timeout: 5000ms  #redis操作的超时时间
        database: 0
        lettuce:
            pool:
              # 连接池中的最大空闲连接
              max-idle: 500
              # 连接池中的最小空闲连接
              min-idle: 200
              # 连接池最大连接数（使用负值表示没有限制）
              max-active: 2000
              # 连接池最大阻塞等待时间（使用负值表示没有限制）
              max-wait: 5000ms
              test-on-create: false
              test-on-borrow: true
              test-on-return: false
              test-while-idle: true
    elasticsearch:
        jest:
            uris: http://192.168.254.201:9200
    data:
      elasticsearch:
        cluster-name: my-application
        cluster-nodes: 192.168.254.201:9300


#自定义：控制shiro集群和非集群
lzxuni:
    redis:
        open: false  # 是否开启redis缓存  true开启   false关闭
    shiro:
        redis: false # true表示shiro session存到redis里，需要开启redis，才会生效【分布式场景】
#mybatis 插件
mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.lzxuni.domain
  global-config:
      #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: 3
      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      field-strategy: 2
      #驼峰下划线转换
      db-column-underline: true
      #刷新mapper 调试神器
      refresh-mapper: true
      #数据库大写下划线转换
      #capital-mode: true
      #序列接口实现类配置
      #key-generator: com.baomidou.springboot.xxx
      #逻辑删除配置
      logic-delete-value: -1
      logic-not-delete-value: 0
      #自定义填充策略接口实现
      #meta-object-handler: com.baomidou.springboot.xxx
      #自定义SQL注入器
      sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
  configuration:
      map-underscore-to-camel-case: true
      cache-enabled: false
      call-setters-on-nulls: true
#springboot 监控点
management:
  endpoints:
    web:
      exposure:
        include: "*"
#          - auditevents
#          - beans
#          - conditions
#          - configprops
#          - env
#          - flyway
#          - health
#          - httptrace
#          - info
#          - loggers
#          - liquibase
#          - metrics
#          - mappings
#          - scheduledtasks
#          - sessions
#          - shutdown
#          - threaddump
  endpoint:
    health:
      show-details: always